### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by benwaffle** [ghik/silencer#24]
```
[error] java.lang.NullPointerException
[error] 	at com.github.ghik.silencer.SuppressingReporter.relativize(SuppressingReporter.scala:62)
[error] 	at com.github.ghik.silencer.SuppressingReporter.$anonfun$info0$2(SuppressingReporter.scala:36)
[error] 	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
[error] 	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
[error] 	at com.github.ghik.silencer.SuppressingReporter.$anonfun$info0$1(SuppressingReporter.scala:37)
[error] 	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
[error] 	at com.github.ghik.silencer.SuppressingReporter.matchesPathFilter$1(SuppressingReporter.scala:34)
[error] 	at com.github.ghik.silencer.SuppressingReporter.info0(SuppressingReporter.scala:46)
[error] 	at com.github.ghik.silencer.SuppressingReporter.info0(SuppressingReporter.scala:11)
[error] 	at scala.reflect.internal.Reporter.warning(Reporting.scala:90)
[error] 	at scala.tools.nsc.Reporting$PerRunReporting$ConditionalWarning.$anonfun$summarize$2(Reporting.scala:58)
[error] 	at scala.tools.nsc.Reporting$PerRunReporting$ConditionalWarning.$anonfun$summarize$2$adapted(Reporting.scala:53)
[error] 	at scala.collection.mutable.RedBlackTree$.foreachNodeNonNull(RedBlackTree.scala:443)
[error] 	at scala.collection.mutable.RedBlackTree$.foreachNodeNonNull(RedBlackTree.scala:442)
[error] 	at scala.collection.mutable.RedBlackTree$.foreach(RedBlackTree.scala:439)
[error] 	at scala.collection.mutable.TreeMap.foreach(TreeMap.scala:104)
[error] 	at scala.tools.nsc.Reporting$PerRunReporting$ConditionalWarning.summarize(Reporting.scala:53)
[error] 	at scala.tools.nsc.Reporting$PerRunReporting.$anonfun$summarizeErrors$1(Reporting.scala:123)
[error] 	at scala.tools.nsc.Reporting$PerRunReporting.summarizeErrors(Reporting.scala:123)
[error] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1543)
[error] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1482)
[error] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1475)
[error] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1598)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
[error] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by benwaffle** [comment]
Using silencer 1.3.0

**Comment by ghik** [comment]
This is probably the same issue as #21 - please upgrade to newest version (1.3.2) and check if the problem disappears.
